pull_request_rules:
  - name: Automatically merge dependency updates
    conditions:
      - author=dependabot[bot]
      - status-success=Test / Verify with Maven
      - base=master
    actions:
      merge:
        method: squash
        commit_message: title+body
      delete_head_branch: {} # Optional: Deletes the branch after merge