pull_request_rules:
  - name: Automatically merge dependency updates
    conditions:
      - author=dependabot[bot]
      - status-success=build
      - base=master
    actions:
      merge:
        method: squash
      delete_head_branch: {} # Optional: Deletes the branch after merge